version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 27.0.0
    - 28.0.0
    - 28.0.1
    - 28.0.2
    - 29.0.0
    - 30.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: socket.io
    versions:
    - 3.1.0
